version: 2.1

parameters:
  debug:
    type: boolean
    default: false  # Default value for debug parameter

orbs:
  slack: circleci/slack@4.12.5  # Slack orb for notifications

commands:
  ecr_push:
    description: "Authenticate, tag & push Docker image to AWS ECR"
    parameters:
      image_name:
        type: string
      tag:
        type: string
        default: << pipeline.git.branch >>
    steps:
      - run:
          name: "Login to AWS ECR"
          command: | # get-login-password output into docker login, so we need pipe between commands
            aws ecr get-login-password \
              --region $AWS_REGION \
            | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL
      - run:
          name: "Tag & Push Docker image"
          command: |
            docker tag <<parameters.image_name>>:<<parameters.tag>> \
              $AWS_ECR_ACCOUNT_URL/<<parameters.image_name>>:<<parameters.tag>>
            docker push $AWS_ECR_ACCOUNT_URL/<<parameters.image_name>>:<<parameters.tag>>

jobs:
  fast-build:
    docker:
      - image: cimg/openjdk:17.0  # Base executor image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true   # Enable DLC
      - run:
          name: Build JAR using Gradle
          command: ./gradlew clean build

  build_image_and_push:
    docker:
      - image: cimg/aws:2025.01  # includes AWS CLI
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true   # Enable DLC
      - run:
         name: Build Docker image locally
         command: docker build -t booking-service:$CIRCLE_SHA1 .
      - ecr_push:
          image_name: booking-service  # Name of the Docker image
          tag: $CIRCLE_SHA1  # Push the Docker image to AWS ECR with the commit SHA as the tag

  build:
    machine:
      image: default
      docker_layer_caching: true  # Enable Docker Layer Caching (DLC). CircleCI retains the Docker cache layers in a shared external volume.
    steps:
      - checkout
      - run:
          name: Build JAR using Gradle
          command: ./gradlew clean build
      - run:
          name: Build Docker image locally
          command: docker build -t booking-service:latest .
      - run:
          name: Save docker image to a file
          command: docker save booking-service:latest -o booking-service.tar
      - persist_to_workspace:
          root: .
          paths:
            - booking-service.tar  # Save the Docker image tar file to workspace
      - ecr_push:
          image_name: booking-service  # Name of the Docker image
          tag: $CIRCLE_SHA1  # Push the Docker image to AWS ECR with the commit SHA as the tag

  test:
    docker:
      - image: cimg/openjdk:17.0  # Base executor image
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew clean test
  #test:
  #  machine:
  #    image: default
  #  steps:
  #    - attach_workspace:
  #        at: /tmp/workspace
  #    - run:
  #        name: Load docker image
  #        command: docker load -i /tmp/workspace/booking-service.tar
  #    - run:
  #        name: Run Tests
  #        command: docker run --rm booking-service:latest ./gradlew test
  notify:
    machine:
      image: default
    steps:
      - run:
          name: send Slack notification
          command: echo "Build and test completed successfully!"
      - slack/notify:
          event: pass
          channel: '#build-notifications'
          template: basic_success_1
workflows:
  build_and_test:
    when: << pipeline.parameters.debug >>  # Run this workflow only if debug is true
    jobs:
      - build
      - test:
          requires:
            - build  # Only runs after build passes
      - notify:
          requires:
            - test  #Only runs after test passes
  fast_build_and_test:
    when: not << pipeline.parameters.debug >>  # Run this workflow only if debug is false
    jobs:
      - fast-build:
      - build_image_and_push:
          requires:
            - fast-build  # Only runs after unit-test passes
      - test:
          requires:
            - fast-build # Only runs after fast-build passes
      - notify:
          requires:
            - test  # Only runs after test passes