version: 2.1

orbs:
  slack: circleci/slack@4.12.5  # Slack orb for notifications

jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true   # Enable DLC
      - run:
          name: Build JAR using Gradle
          command: ./gradlew clean build
      - run:
          name: Build Docker image locally
          command: docker build -t booking-service:latest .
      - run:
          name: Save docker image to a file
          command: docker save booking-service:latest -o booking-service.tar
      - persist_to_workspace:
          root: .
          paths:
            - booking-service.tar  # Save the Docker image tar file to workspace
  test:
    docker:
      - image: cimg/openjdk:17.0  # Base executor image
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew clean test
  #test:
  #  machine:
  #    image: default
  #  steps:
  #    - attach_workspace:
  #        at: /tmp/workspace
  #    - run:
  #        name: Load docker image
  #        command: docker load -i /tmp/workspace/booking-service.tar
  #    - run:
  #        name: Run Tests
  #        command: docker run --rm booking-service:latest ./gradlew test
  notify:
    machine:
      image: default
    steps:
      - run:
          name: send Slack notification
          command: echo "Build and test completed successfully!"
      - slack/notify:
          event: pass
          channel: '#build-notifications'
          template: basic_success_1
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build  # Only runs after build passes
      - notify:
          requires:
            - test  #Only runs after test passes